version: "1.0"
services:
  app:
    container_name: friction-report-api
    image: friction-report-api
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AWS_REGION: ${AWS_REGION}