version: '1.0'
services:
  api:
    container_name: friction-report-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      H2_USERNAME: ${H2_USERNAME}
      H2_PASSWORD: ${H2_PASSWORD}
    ports:
      - 8080:8080