server:
  port: 8080

logging:
  level:
    root: INFO
  file:
    name: '/logs/friction-report/friction-report.log'

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:areadb;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

api:
  key: ${OPEN_WEATHER_API_KEY}
---
spring:
  config:
    activate:
      on-profile: prod

api:
  key: ${OPEN_WEATHER_API_KEY}